# Site settings
title:  "Resume Eduard Dedu"
description:  "A Jekyll and GitHub Pages site."

# Build settings
markdown:  kramdown
sass:
  sass_dir:  _sass
  style:  compressed

# Resume settings
resume_avatar:                          "true"
resume_name:                            "Eduard Dedu"
resume_title:                           "Java Developer"
resume_contact_email:                   "eduardcdedu@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:                "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:              true
resume_section_education:               true
resume_section_projects:                true
resume_section_tech:                  	true
resume_section_links:                   false
resume_section_books:            		    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:                
  resume_github_url:                  "https://github.com/eduarddedu"
  resume_hackerrank_url:              "https://www.hackerrank.com/eduarddedu"
  resume_website_url:                 "https://blog.codecritique.org/"
  #resume_linkedin_url:                "https://www.linkedin.com/in/eduard-dedu-b4508a5a"
  #resume_facebook_url:                "https://www.facebook.com/eduardcdedu"



# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
